services:
  mysql:
    image: 'mysql:latest'
    platform: linux/amd64
    restart: always
    environment:
      - 'MYSQL_DATABASE=splearn_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=spring'
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
